I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 360, in script
    show monster at Transform(scale=0.5) with dissolve
  File "game/script.rpy", line 360, in <module>
    show monster at Transform(scale=0.5) with dissolve
Exception: Unknown transform property: 'scale'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 360, in script
    show monster at Transform(scale=0.5) with dissolve
  File "C:\Users\rulkennedy\OneDrive\Documents\Kuliah\Semester 7\Game\renpy-8.3.2-sdk\renpy\ast.py", line 1111, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\rulkennedy\OneDrive\Documents\Kuliah\Semester 7\Game\renpy-8.3.2-sdk\renpy\ast.py", line 1070, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\rulkennedy\OneDrive\Documents\Kuliah\Semester 7\Game\renpy-8.3.2-sdk\renpy\ast.py", line 1070, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\rulkennedy\OneDrive\Documents\Kuliah\Semester 7\Game\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\rulkennedy\OneDrive\Documents\Kuliah\Semester 7\Game\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 360, in <module>
    show monster at Transform(scale=0.5) with dissolve
  File "C:\Users\rulkennedy\OneDrive\Documents\Kuliah\Semester 7\Game\renpy-8.3.2-sdk\renpy\display\transform.py", line 745, in __init__
    raise Exception("Unknown transform property: %r" % k)
Exception: Unknown transform property: 'scale'

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090902
Fantasy Ren'py GUI template 1.0
Fri Nov  1 14:51:28 2024
